### ISSUE TITLE
Make Git.remote and Git.revision mandatory fields.

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/ci-environment#36]
**Is your feature request related to a problem? Please describe.**

Some optional fields should be mandatory and vice versa.

**Describe the solution you'd like**

```typescript
export type CiEnvironment = {
  name: string
  url: string
  buildNumber: string
  git?: Git
}

export type Git = {
  remote: string
  revision: string
  branch?: string
  tag?: string
}
```

If `remote` or `revision` cannot be determined, don't create a `Git` object at all. Those two fields are the bare minimum for useful git information.

**Comment by aslakhellesoy** [comment]
WDYT @davidjgoss @aurelien-reeves

**Comment by aurelien-reeves** [comment]
I agree with this proposition 👍
