### ISSUE TITLE
Commit SHA for GitHub Actions is incorrect for Pull requests

### ISSUE THREAD

**Issue by vincent-psarga** [cucumber/ci-environment#67]
**Describe the bug**

The commit SHA provided in a PR is not the SHA of the last commit in this PR (instead, it's a merge commit between the last commit and the base branch, usually `main`).

**Additional context**

Some extra infos and a potential solution here: https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286/3

**Comment by aslakhellesoy** [comment]
Fixed by #69
